global function initFrontierDefenseData
void function initFrontierDefenseData()
{
	useCustomFDLoad = true
	AddCallback_RegisterCustomFDContent( RegisterCustomFDContent )
    shopPosition = < -2811, -1176, 128 >
	shopAngles = < 0, 0, 0 >
	FD_spawnPosition = < -2616.61, -496.03, 48 >
	FD_spawnAngles = < 0, 0, 0 >
	FD_groundspawnPosition = < -3126, -1181, 129 >
	FD_groundspawnAngles = < 0, 0, 0 >
	
	FD_DropPodSpawns.append(< -2906, -265, 264 >)
	FD_DropPodSpawns.append(< -4569, -647, 314 >)
	FD_DropPodSpawns.append(< -2950, -1857, 268 >)
	
	waveAnnouncement.append("fd_introMedium")
	waveAnnouncement.append("fd_waveTypeReaperTicks")
	waveAnnouncement.append("fd_waveTypeCloakDrone")
	waveAnnouncement.append("fd_introHard")
	waveAnnouncement.append("fd_waveComboNukeTrain")

	int index = 1
	array<vector> infantrySpawns = []
	infantrySpawns.append(< -606, -362, 3 >)
	infantrySpawns.append(< -169, -800, -1 >)
	infantrySpawns.append(< -1092, -1299, 37 >)
	infantrySpawns.append(< -1747, -311, 272 >)
	infantrySpawns.append(< -1261, -121, 272 >)
	infantrySpawns.append(< 563, -825, 54 >)
	infantrySpawns.append(< -209, 1078, -1 >)
	infantrySpawns.append(< -965, 1076, 53 >)
	infantrySpawns.append(< 1171, 408, 272 >)
	infantrySpawns.append(< 1312, 665, 267 >)
	infantrySpawns.append(< 1432, 1419, 271 >)
	infantrySpawns.append(< 289, 676, 0 >)
	
	array<vector> reaperSpawns = []
	reaperSpawns.append(< 1666, 1392, 272 >)
	reaperSpawns.append(< 2429, 1435, 127 >)
	reaperSpawns.append(< 1224, 509, 272 >)
	reaperSpawns.append(< 3747, 2084, 37 >)
	reaperSpawns.append(< 3674, -217, 29 >)
	reaperSpawns.append(< 3185, 1131, 0 >)
	reaperSpawns.append(< 427, 2277, 15 >)
	reaperSpawns.append(< 565, -1294, 5 >)
	reaperSpawns.append(< 3211, 2594, 19 >)
	reaperSpawns.append(< -571, -178, 0 >)
	
	array<vector> titanSpawns = []
	titanSpawns.append(< 3543, 2036, 14 >)
	titanSpawns.append(< 3638, 1175, -10 >)
	titanSpawns.append(< 3188, 628, 30 >)
	titanSpawns.append(< 3472, 343, 13 >)
	titanSpawns.append(< 3315, -171, 23 >)
	titanSpawns.append(< 2134, -608, 48 >)
	titanSpawns.append(< 3146, 2516, -4 >)
	titanSpawns.append(< 2178, 2187, 90 >)
	titanSpawns.append(< 2356, 2545, 30 >)
	titanSpawns.append(< 3670, 883, 5 >)
	titanSpawns.append(< 3217, 1705, 19 >)
	
	array<vector> specialTitanSpawns = []
	specialTitanSpawns.append(< 1972, 993, 17 >)
	specialTitanSpawns.append(< 2663, -1, 33 >)
	specialTitanSpawns.append(< 1369, 2576, 63 >)
	specialTitanSpawns.append(< 1889, 2242, 102 >)
	specialTitanSpawns.append(< 3277, 2127, 17 >)
	specialTitanSpawns.append(< 478, 2205, 3 >)
	
	int spawnamount

    array<WaveEvent> wave1
	wave1.append(CreateSmokeEvent(< -177, 1610, 2 >, 90, index++))
	wave1.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave1.append(CreateSmokeEvent(< -2243, 931, 34 >, 90, index++))
	wave1.append(CreateWaitForTimeEvent( 0.8, index++ ) )
	wave1.append(CreateSmokeEvent(< -2287, -667, 18 >, 90, index++))
	wave1.append(CreateWaitForTimeEvent( 0.6, index++ ) )
	wave1.append(CreateSmokeEvent(< -1179, -884, -13 >, 90, index++))
	wave1.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave1.append(CreateSmokeEvent(< -1887, -1701, 61 >, 90, index++))
	wave1.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave1.append(CreateSmokeEvent(< -3135, 350, 18 >, 90, index++))
	wave1.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave1.append(CreateWarningEvent( FD_IncomingWarnings.Infantry, index++ ))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.5, 1.2 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.5, 1.2 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.5, 1.2 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave1.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave1.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave1.append(CreateWarningEvent( FD_IncomingWarnings.Stalkers, index++ ))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave1.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave1.append(CreateWarningEvent( FD_IncomingWarnings.MortarSpectre, index++ ))
	wave1.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave1.append(CreateWaitUntilAliveEvent( 8, index++ ) )
	wave1.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave1.append(CreateWaitUntilAliveEvent( 8, index++ ) )
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.3, 0.8 ),index++))
	wave1.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",0))
    waveEvents.append(wave1)
	index = 1
	array<WaveEvent> wave2
	wave2.append(CreateWarningEvent( FD_IncomingWarnings.EnemyTitansIncoming, index++ ))
	wave2.append(CreateMonarchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateMonarchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateMonarchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave2.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	wave2.append(CreateToneTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateIonTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateIonTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave2.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	wave2.append(CreateLegionTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateRoninTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateRoninTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave2.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	wave2.append(CreateWarningEvent( FD_IncomingWarnings.ReaperAlt, index++ ))
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave2.append(CreateIonTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave2.append(CreateIonTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.4, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave2.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave2.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave2.append(CreateSuperSpectreEventWithMinion( < 2516, 368, 255 > ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodSpectreMortarEvent( < 2147, 139, 176 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateRoninTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateRoninTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave2.append(CreateWaitUntilAliveEvent( 2, index++ ) )
	wave2.append(CreateIonTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateLegionTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateScorchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateLegionTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateIonTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave2.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave2.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave2.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave2.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",0))
    waveEvents.append(wave2)
	index = 1
	array<WaveEvent> wave3
	wave3.append(CreateSmokeEvent(< 3719, 1924, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< -258, 1569, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 3168, 866, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 3592, 464, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 3095, 385, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 764, 2425, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 1809, -237, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 2736, 1872, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 1683, 2418, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 748, 1091, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 2290, 2371, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 325, 1688, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 3588, 1291, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 711, 1474, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 1881, 892, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 3291, 1839, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 1210, -793, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 1815, 241, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 3496, -65, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 2242, -225, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 3015, 2413, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 1348, 1044, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 2084, 1859, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 2843, -72, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 645, -937, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 874, 1817, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 1828, -692, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 325, -1421, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 2558, 879, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 80, 701, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< 1486, 1899, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave3.append(CreateSmokeEvent(< -282, -1319, 144 >, 300, index++))
	wave3.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateWarningEvent( FD_IncomingWarnings.CloakDrone, index++ ))
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave3.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave3.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave3.append(CreateWarningEvent( FD_IncomingWarnings.MortarTitanIntro, index++ ))
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.3, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.3, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.6, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.6, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave3.append(CreateWaitUntilAliveEvent( 2, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.3, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.3, index++ ) )
	wave3.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.6, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.6, index++ ) )
	wave3.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave3.append(CreateWaitUntilAliveEvent( 2, index++ ) )
	wave3.append(CreateWarningEvent( FD_IncomingWarnings.ComboArcMortar, index++ ))
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave3.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateSuperSpectreEventWithMinion( < 2516, 368, 255 > ,< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateDroppodSpectreMortarEvent( < 2147, 139, 176 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave3.append(CreateWaitUntilAliveEvent( 2, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave3.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave3.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave3.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave3.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",0))
    waveEvents.append(wave3)
	index = 1
	array<WaveEvent> wave4
	wave4.append(CreateScorchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateScorchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateScorchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave4.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave4.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave4.append(CreateWarningEvent( FD_IncomingWarnings.PreNukeTitan, index++ ))
	wave4.append(CreateWaitUntilAliveEvent( 2, index++ ) )
	wave4.append(CreateToneTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateToneTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateToneTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave4.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave4.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave4.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	wave4.append(CreateIonTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateToneTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateMonarchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateWarningEvent( FD_IncomingWarnings.NukeTitanIntro, index++ ))
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave4.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave4.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.6, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.6, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.6, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.6, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateSuperSpectreEventWithMinion( < 2516, 368, 255 > ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateDroppodSpectreMortarEvent( < 2147, 139, 176 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave4.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave4.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave4.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	wave4.append(CreateWarningEvent( FD_IncomingWarnings.EliteTitan, index++ ))
	wave4.append(CreateNorthstarSniperTitanEvent( specialTitanSpawns.getrandom() ,< 0, 180, 0 >,index++,1,"",FD_TitanType.TITAN_ELITE))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateNorthstarSniperTitanEvent( specialTitanSpawns.getrandom() ,< 0, 180, 0 >,index++,1,"",FD_TitanType.TITAN_ELITE))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateNorthstarSniperTitanEvent( specialTitanSpawns.getrandom() ,< 0, 180, 0 >,index++,1,"",FD_TitanType.TITAN_ELITE))
	wave4.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave4.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	wave4.append(CreateRoninTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateRoninTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateRoninTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave4.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave4.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave4.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave4.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave4.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave4.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave4.append(CreateNorthstarSniperTitanEvent( specialTitanSpawns.getrandom() ,< 0, 180, 0 >,index++,1,"",FD_TitanType.TITAN_ELITE))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateNorthstarSniperTitanEvent( specialTitanSpawns.getrandom() ,< 0, 180, 0 >,index++,1,"",FD_TitanType.TITAN_ELITE))
	wave4.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave4.append(CreateNorthstarSniperTitanEvent( specialTitanSpawns.getrandom() ,< 0, 180, 0 >,0,1,"",FD_TitanType.TITAN_ELITE))
    waveEvents.append(wave4)
	index = 1
	array<WaveEvent> wave5
	wave5.append(CreateWarningEvent( FD_IncomingWarnings.Everything, index++ ))
	wave5.append(CreateIonTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateLegionTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateScorchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateLegionTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateIonTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEvent( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave5.append(CreateWarningEvent( FD_IncomingWarnings.ComboArcNuke, index++ ))
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave5.append(CreateNorthstarSniperTitanEvent( specialTitanSpawns.getrandom() ,< 0, 180, 0 >,index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave5.append(CreateNorthstarSniperTitanEvent( specialTitanSpawns.getrandom() ,< 0, 180, 0 >,index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave5.append(CreateNorthstarSniperTitanEvent( specialTitanSpawns.getrandom() ,< 0, 180, 0 >,index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave5.append(CreateSuperSpectreEventWithMinion( < 2516, 368, 255 > ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodSpectreMortarEvent( < 2147, 139, 176 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave5.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateSuperSpectreEventWithMinion( reaperSpawns.getrandom() ,< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWarningEvent( FD_IncomingWarnings.MortarTitan, index++ ))
	wave5.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 1.5, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave5.append(CreateRoninTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateRoninTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateRoninTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodSpectreMortarEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodGruntEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateLegionTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateLegionTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave5.append(CreateScorchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateScorchTitanEvent( titanSpawns.getrandom() ,< 0 , 180 , 0 >,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave5.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWaitUntilAliveEvent( 0, index++ ) )
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWarningEvent( FD_IncomingWarnings.TitanfallBlocked, index++ ))
	wave5.append(CreateTitanfallBlockEvent( 1, index++ ) )
	wave5.append(CreateSmokeEvent(< 2242, -225, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -243, -795, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 874, 1817, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -2242, -2140, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 2736, 1872, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -2468, -1608, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -2243, -362, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -962, -1887, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -3049, -1672, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -753, -1403, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 1809, -237, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 325, -1421, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 711, 1474, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 645, -937, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 764, 2425, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -2256, 914, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 1683, 2418, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 1881, 892, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -2191, 211, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 80, 701, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 3496, -65, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -3192, 314, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 2843, -72, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 1815, 241, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 1348, 1044, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -282, -1319, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -1758, -2221, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 3095, 385, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 3291, 1839, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -3764, -1995, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -3495, -1618, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 748, 1091, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -1078, 1092, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 2084, 1859, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -1156, -1301, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 3015, 2413, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 2558, 879, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -1933, -808, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -2699, -2124, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -833, 1594, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -4054, -1672, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -3221, -2194, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -1669, 1037, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 325, 1688, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 1210, -793, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 3592, 464, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 3168, 866, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -1237, -2231, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 2290, 2371, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -198, -66, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 3719, 1924, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -1457, -1721, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -2746, -659, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -604, -362, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 3588, 1291, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -1946, -1667, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -3237, -691, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -1366, -833, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -258, 1569, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -817, -833, 143 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 27, 462, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 1486, 1899, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< 1828, -692, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 0.2, index++ ) )
	wave5.append(CreateSmokeEvent(< -2617, 475, 144 >, 300, index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWarningEvent( FD_IncomingWarnings.NukeTitan, index++ ))
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWaitUntilAliveEvent( 8, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateMortarTitanEvent( specialTitanSpawns.getrandom() ,< 0 , 180 , 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave5.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateArcTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateDroppodStalkerEvent( infantrySpawns.getrandom(),"",index++))
	wave5.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 1.0, index++ ) )
	wave5.append(CreateCloakDroneEvent( titanSpawns.getrandom() + < 0, 0, 2500 >,< 0, 180, 0 >,index++))
	wave5.append(CreateWaitForTimeEvent( 2.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",index++))
	wave5.append(CreateWaitForTimeEvent( 0.5, index++ ) )
	wave5.append(CreateNukeTitanEvent( titanSpawns.getrandom(),< 0, 180, 0 >,"",0))
    waveEvents.append(wave5)
}

void function RegisterCustomFDContent()
{
	array<entity> aiPositions = GetEntArrayByClass_Expensive( "info_target" )
	foreach ( entity position in aiPositions )
		if( position.HasKey( "editorclass" ) && position.kv.editorclass == "info_fd_ai_position" )
			position.Destroy()
		
	AddFDCustomTitanStart( < -3998, 374, 22 >, < 0, -45, 0 > )
	AddFDCustomTitanStart( < -4068, -1818, 31 >, < 0, 45, 0 > )
	
	AddStationaryAIPosition(< 1724, 1079, 3 >, eStationaryAIPositionTypes.MORTAR_TITAN)
	AddStationaryAIPosition(< 1991, -210, -12 >, eStationaryAIPositionTypes.MORTAR_TITAN)
	AddStationaryAIPosition(< 2917, 2182, 4 >, eStationaryAIPositionTypes.MORTAR_TITAN)
	AddStationaryAIPosition(< 1506, 2299, 100 >, eStationaryAIPositionTypes.MORTAR_TITAN)
	AddStationaryAIPosition(< 197, 460, 0 >, eStationaryAIPositionTypes.MORTAR_TITAN)
	AddStationaryAIPosition(< 897, 1408, 33 >, eStationaryAIPositionTypes.MORTAR_TITAN)
	AddStationaryAIPosition(< 3119, 186, 19 >, eStationaryAIPositionTypes.MORTAR_TITAN)
	AddStationaryAIPosition(< 3688, 1347, 0 >, eStationaryAIPositionTypes.MORTAR_TITAN)
	
	AddStationaryAIPosition(< 2598, 543, 264 >, eStationaryAIPositionTypes.MORTAR_SPECTRE)
	AddStationaryAIPosition(< 1274, 1444, 272 >, eStationaryAIPositionTypes.MORTAR_SPECTRE)
	AddStationaryAIPosition(< 1548, 533, 272 >, eStationaryAIPositionTypes.MORTAR_SPECTRE)
	AddStationaryAIPosition(< -1564, -155, 272 >, eStationaryAIPositionTypes.MORTAR_SPECTRE)
	AddStationaryAIPosition(< -1529, -1201, 272 >, eStationaryAIPositionTypes.MORTAR_SPECTRE)
	AddStationaryAIPosition(< 1205, 390, 272 >, eStationaryAIPositionTypes.MORTAR_SPECTRE)
	
	AddStationaryAIPosition(< 2053, -767, 45 >, eStationaryAIPositionTypes.SNIPER_TITAN)
	AddStationaryAIPosition(< 3649, 1832, 10 >, eStationaryAIPositionTypes.SNIPER_TITAN)
	AddStationaryAIPosition(< 3417, 902, 8 >, eStationaryAIPositionTypes.SNIPER_TITAN)
	AddStationaryAIPosition(< 889, 2536, 57 >, eStationaryAIPositionTypes.SNIPER_TITAN)
	AddStationaryAIPosition(< -1248, -800, -7 >, eStationaryAIPositionTypes.SNIPER_TITAN)
	AddStationaryAIPosition(< -2357, 938, 32 >, eStationaryAIPositionTypes.SNIPER_TITAN)
	AddStationaryAIPosition(< -968, -2288, 24 >, eStationaryAIPositionTypes.SNIPER_TITAN)
	
	AddStationaryAIPosition(< 1205, 1063, 301 >, eStationaryAIPositionTypes.LAUNCHER_REAPER)
	AddStationaryAIPosition(< 2088, 480, 327 >, eStationaryAIPositionTypes.LAUNCHER_REAPER)
	AddStationaryAIPosition(< 527, 762, 272 >, eStationaryAIPositionTypes.LAUNCHER_REAPER)
	AddStationaryAIPosition(< -1589, -816, 279 >, eStationaryAIPositionTypes.LAUNCHER_REAPER)
	AddStationaryAIPosition(< -1960, -256, 271 >, eStationaryAIPositionTypes.LAUNCHER_REAPER)
	AddStationaryAIPosition(< 2318, 1169, 128 >, eStationaryAIPositionTypes.LAUNCHER_REAPER)
	AddStationaryAIPosition(< 3544, -50, 18 >, eStationaryAIPositionTypes.LAUNCHER_REAPER)
	AddStationaryAIPosition(< 3371, 2251, 35 >, eStationaryAIPositionTypes.LAUNCHER_REAPER)
	AddStationaryAIPosition(< 2215, -455, 23 >, eStationaryAIPositionTypes.LAUNCHER_REAPER)
	
	routes[ "longStraightL" ] <- []
	routes[ "longStraightL" ].append( < 3360, 1881, 11 > )
	routes[ "longStraightL" ].append( < 705, 1840, 4 > )
	routes[ "longStraightL" ].append( < -938, 1354, 2 > )
	routes[ "longStraightL" ].append( < -2423, 571, -16 > )
	routes[ "longStraightL" ].append( < -2252, -681, 18 > )
	routes[ "longStraightL" ].append( < -3650, -657, 25 > )
	
	routes[ "longStraightC" ] <- []
	routes[ "longStraightC" ].append( < 3300, 903, 26 > )
	routes[ "longStraightC" ].append( < 392, 1100, 4 > )
	routes[ "longStraightC" ].append( < -581, -655, 1 > )
	routes[ "longStraightC" ].append( < -581, -655, 1 > )
	routes[ "longStraightC" ].append( < -2252, -681, 18 > )
	routes[ "longStraightC" ].append( < -3650, -657, 25 > )
	
	routes[ "longStraightR" ] <- []
	routes[ "longStraightR" ].append( < 3292, -7, 32 > )
	routes[ "longStraightR" ].append( < 1153, -797, 3 > )
	routes[ "longStraightR" ].append( < -1082, -1625, 1 > )
	routes[ "longStraightR" ].append( < -3595, -1632, 32 > )
	routes[ "longStraightR" ].append( < -3959, -1138, 1 > )
	
	routes[ "longFullCorner" ] <- []
	routes[ "longFullCorner" ].append( < 1685, 2472, 42 > )
	routes[ "longFullCorner" ].append( < 465, 1698, -9 > )
	routes[ "longFullCorner" ].append( < -967, 1131, 40 > )
	routes[ "longFullCorner" ].append( < -2626, 482, 1 > )
	routes[ "longFullCorner" ].append( < -3826, -267, 13 > )
	
	routes[ "infantryUpperClose" ] <- []
	routes[ "infantryUpperClose" ].append( < -1340, -289, 271 > )
	routes[ "infantryUpperClose" ].append( < -1840, -810, -27 > )
	routes[ "infantryUpperClose" ].append( < -3604, -526, 31 > )
	
	routes[ "infantryUpperFar" ] <- []
	routes[ "infantryUpperFar" ].append( < 1079, 513, 271 > )
	routes[ "infantryUpperFar" ].append( < 729, 1296, -1 > )
	routes[ "infantryUpperFar" ].append( < -921, 1394, 0 > )
	routes[ "infantryUpperFar" ].append( < -2679, 532, 0 > )
	routes[ "infantryUpperFar" ].append( < -3961, -174, 15 > )
	
	routes[ "lowerClose" ] <- []
	routes[ "lowerClose" ].append( < -528, -1029, 21 > )
	routes[ "lowerClose" ].append( < -1478, -1617, 12 > )
	routes[ "lowerClose" ].append( < -3715, -1575, 14 > )
	routes[ "lowerClose" ].append( < -4046, -1146, 2 > )
	
	routes[ "lowerFar" ] <- []
	routes[ "lowerFar" ].append( < 114, 1273, 20 > )
	routes[ "lowerFar" ].append( < -1018, 1142, 31 > )
	routes[ "lowerFar" ].append( < -2387, 559, -15 > )
	routes[ "lowerFar" ].append( < -3675, -369, 5 > )
}