global array<string> kabilities = ["mp_ability_cloak",
			 "mp_ability_grapple",
			 "mp_ability_heal",
			 "mp_ability_holopilot",
			 "mp_ability_holopilot_nova",
			 "mp_ability_shifter",
			 "mp_ability_timeshift",
			 "mp_ability_arc_blast",
			 "mp_ability_shifter_super",
			 "mp_weapon_grenade_sonar",
			 "mp_weapon_deployable_cover"];

global array<string> ordnances = ["mp_weapon_frag_grenade",
			 "mp_weapon_thermite_grenade",
			 "mp_weapon_grenade_electric_smoke",
			 "mp_weapon_grenade_emp",
			 "mp_weapon_satchel",
			 "mp_weapon_frag_drone",
			 "mp_titanweapon_flame_wall",
			 "mp_titanweapon_laser_lite",
			 "mp_titanweapon_arc_wave",
			 "mp_titanweapon_tracker_rockets",
			 "mp_titanweapon_dumbfire_rockets",
			 "mp_titanweapon_shoulder_rockets",
			 "mp_titanweapon_salvo_rockets",
			 "mp_titanability_power_shot"];

global array<string> defensives = ["mp_titanability_gun_shield"
			 "mp_titanweapon_vortex_shield",
			 "mp_titanweapon_heat_shield",
			 "mp_titanweapon_stun_laser",
			 "mp_titanability_tether_trap",
			 "mp_titanability_basic_block",
			 "mp_titanability_particle_wall",
			 "mp_titanability_timeshift"
			 "mp_ability_swordblock"];

global array<string> tacticals = ["mp_titanability_ammo_swap",
			 "mp_titanability_slow_trap",
			 "mp_titanability_laser_trip",
			 "mp_titanability_phase_dash",
			 "mp_titanability_sonar_pulse",
			 "mp_titanability_hover",
			 "mp_titanability_rearm",
			 "mp_titanability_electric_smoke"];

global array<string> cores = ["mp_titancore_laser_cannon",
		 "mp_titancore_salvo_core",
		 "mp_titancore_flame_wave",
		 "mp_titancore_siege_mode",
		 "mp_titancore_flight_core",
		 "mp_titancore_shift_core",
		 "mp_titancore_upgrade",
		 "mp_titancore_amp_core"];

global array<string> melee = ["melee_pilot_emptyhanded",
					  "melee_pilot_sword",
					  "melee_titan_punch_fighter",
					  "melee_titan_punch_tone",
					  "melee_titan_punch_ion",
					  "melee_titan_punch_northstar",
					  "melee_titan_punch_scorch",
					  "melee_titan_punch_legion",
					  "melee_titan_punch_vanguard",
					  "melee_titan_sword",
					  "melee_titan_sword_aoe",
					  "melee_pilot_kunai",
					  "melee_pilot_arena"];

 global array<string> customweapon = ["mp_weapon_arc_trap",
								"mp_weapon_peacekraber",
								"mp_weapon_gunship_turret",
								"mp_weapon_gunship_launcher",
								"mp_weapon_gunship_missile",
								"mp_weapon_hard_cover",
								"mp_weapon_arena1",
								"mp_weapon_arena2",
								"mp_weapon_arena3",
								"mp_ability_turretweapon",
								"mp_weapon_smart_pistol"
								"mp_ability_holopilot_nova",
								"mp_titanweapon_flightcore_rockets"]

global array<string> kmods = ["extended_ammo",
					 "silencer",
					 "hcog",
					 "redline_sight",
					 "aog",
					 "holosight",
					 "scope_4x",
					 "ricochet",
					 "threat_scope",
					 "quick_charge",
					 "tactical_cdr_on_kill",
					 "pas_fast_ads",
					 "pas_fast_swap",
					 "pas_fast_reload",
					 "pro_screen",
					 "pas_run_and_gun"];