global function SP_CRASHSITE_AutoPrecache

void function SP_CRASHSITE_AutoPrecache()
{
#if DEV
	#if SERVER
	SetAutoPrecacheVersion( 5 )
	// NPC spawners found:
	AP_NPCSpawnerFound( "npc_drone_beam", 8 )
	AP_NPCSpawnerFound( "npc_drone_plasma", 4 )
	AP_NPCSpawnerFound( "npc_prowler", 11 )
	AP_NPCSpawnerFound( "npc_soldier", 64 )
	AP_NPCSpawnerFound( "npc_soldier_shield_captain", 1 )
	AP_NPCSpawnerFound( "npc_soldier_specialist", 1 )
	AP_NPCSpawnerFound( "npc_spectre", 61 )
	AP_NPCSpawnerFound( "npc_titan_atlas_stickybomb", 1 )
	AP_NPCSpawnerFound( "npc_titan_atlas_tracker", 1 )
	AP_NPCSpawnerFound( "npc_titan_ogre_minigun", 1 )
	AP_NPCSpawnerFound( "npc_titan_stryder_leadwall", 2 )
	AP_NPCSpawnerFound( "npc_titan_stryder_rocketeer", 2 )
	AP_NPCSpawnerFound( "npc_turret_sentry_plasma", 1 )
	#endif

	AP_PrecacheWeapon( "melee_pilot_emptyhanded", 1 )
	AP_PrecacheWeapon( "melee_titan_punch", 5 )
	AP_PrecacheWeapon( "melee_titan_punch_ion", 3 )
	AP_PrecacheWeapon( "melee_titan_punch_legion", 3 )
	AP_PrecacheWeapon( "melee_titan_punch_northstar", 1 )
	AP_PrecacheWeapon( "melee_titan_punch_scorch", 1 )
	AP_PrecacheWeapon( "melee_titan_punch_tone", 3 )
	AP_PrecacheWeapon( "melee_titan_sword", 4 )
	AP_PrecacheWeapon( "mp_titanability_ammo_swap", 3 )
	AP_PrecacheWeapon( "mp_titanability_basic_block", 4 )
	AP_PrecacheWeapon( "mp_titanability_gun_shield", 3 )
	AP_PrecacheWeapon( "mp_titanability_hover", 5 )
	AP_PrecacheWeapon( "mp_titanability_laser_trip", 3 )
	AP_PrecacheWeapon( "mp_titanability_particle_wall", 3 )
	AP_PrecacheWeapon( "mp_titanability_phase_dash", 4 )
	AP_PrecacheWeapon( "mp_titanability_power_shot", 3 )
	AP_PrecacheWeapon( "mp_titanability_slow_trap", 1 )
	AP_PrecacheWeapon( "mp_titanability_smoke", 1 )
	AP_PrecacheWeapon( "mp_titanability_sonar_pulse", 3 )
	AP_PrecacheWeapon( "mp_titanability_tether_trap", 1 )
	AP_PrecacheWeapon( "mp_titancore_amp_core", 1 )
	AP_PrecacheWeapon( "mp_titancore_flame_wave", 1 )
	AP_PrecacheWeapon( "mp_titancore_flight_core", 5 )
	AP_PrecacheWeapon( "mp_titancore_laser_cannon", 3 )
	AP_PrecacheWeapon( "mp_titancore_salvo_core", 3 )
	AP_PrecacheWeapon( "mp_titancore_shift_core", 4 )
	AP_PrecacheWeapon( "mp_titancore_siege_mode", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_arc_wave", 4 )
	AP_PrecacheWeapon( "mp_titanweapon_dumbfire_rockets", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_flame_wall", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_heat_shield", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_laser_lite", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_leadwall", 4 )
	AP_PrecacheWeapon( "mp_titanweapon_meteor", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_particle_accelerator", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_predator_cannon", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_rocketeer_rocketstream", 4 )
	AP_PrecacheWeapon( "mp_titanweapon_shoulder_rockets", 5 )
	AP_PrecacheWeapon( "mp_titanweapon_sniper", 1 )
	AP_PrecacheWeapon( "mp_titanweapon_sticky_40mm", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_tracker_rockets", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_vortex_shield", 5 )
	AP_PrecacheWeapon( "mp_titanweapon_vortex_shield_ion", 3 )
	AP_PrecacheWeapon( "mp_titanweapon_xo16_shorty", 1 )
	AP_PrecacheWeapon( "mp_weapon_car", 2 )
	AP_PrecacheWeapon( "mp_weapon_dmr", 3 )
	AP_PrecacheWeapon( "mp_weapon_dronebeam", 1 )
	AP_PrecacheWeapon( "mp_weapon_droneplasma", 1 )
	AP_PrecacheWeapon( "mp_weapon_frag_drone", 1 )
	AP_PrecacheWeapon( "mp_weapon_frag_grenade", 67 )
	AP_PrecacheWeapon( "mp_weapon_grenade_emp", 1 )
	AP_PrecacheWeapon( "mp_weapon_hemlok", 5 )
	AP_PrecacheWeapon( "mp_weapon_hemlok_smg", 6 )
	AP_PrecacheWeapon( "mp_weapon_lmg", 1 )
	AP_PrecacheWeapon( "mp_weapon_rocket_launcher", 2 )
	AP_PrecacheWeapon( "mp_weapon_rspn101", 8 )
	AP_PrecacheWeapon( "mp_weapon_semipistol", 3 )
	AP_PrecacheWeapon( "mp_weapon_shotgun", 3 )
	AP_PrecacheWeapon( "mp_weapon_smr", 2 )
	AP_PrecacheWeapon( "mp_weapon_turretplasma", 1 )
	AP_PrecacheWeapon( "mp_weapon_vinson", 15 )
	AP_PrecacheModel( $"models/Humans/heroes/imc_hero_slone.mdl" )
	AP_PrecacheModel( $"models/creatures/prowler/r2_prowler.mdl" )
	AP_PrecacheModel( $"models/gibs/human_gibs.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib7_r_shin.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh2.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib9_l_bicep1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_hatch_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm2_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm2_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/og_gib_hatch_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/og_gib_r_forarm_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib7_r_shin.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib8_l_thigh1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib8_l_thigh2.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib9_l_bicep1.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_hatch_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_l_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_l_arm2_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_r_arm1_d.mdl" )
	AP_PrecacheModel( $"models/gibs/titan_gibs/stry_gib_r_arm2_d.mdl" )
	AP_PrecacheModel( $"models/humans/grunts/imc_grunt_rifle.mdl" )
	AP_PrecacheModel( $"models/humans/grunts/imc_grunt_shield_captain.mdl" )
	AP_PrecacheModel( $"models/humans/grunts/mlt_grunt_rifle.mdl" )
	AP_PrecacheModel( $"models/humans/heroes/imc_hero_ash.mdl" )
	AP_PrecacheModel( $"models/humans/heroes/imc_hero_blisk.mdl" )
	AP_PrecacheModel( $"models/humans/heroes/mlt_hero_jack_rifleman.mdl" )
	AP_PrecacheModel( $"models/humans/pilots/sp_light_ged_m.mdl" )
	AP_PrecacheModel( $"models/robots/aerial_unmanned_worker/aerial_unmanned_worker.mdl" )
	AP_PrecacheModel( $"models/robots/drone_air_attack/drone_air_attack_plasma.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/imc_spectre.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_arm_l.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_arm_r.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_leg_l.mdl" )
	AP_PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_leg_r.mdl" )
	AP_PrecacheModel( $"models/robots/turret_plasma/turret_plasma.mdl" )
	AP_PrecacheModel( $"models/titans/buddy/titan_buddy.mdl" )
	AP_PrecacheModel( $"models/titans/heavy/sp_titan_heavy_deadbolt.mdl" )
	AP_PrecacheModel( $"models/titans/heavy/titan_heavy_rodeo_battery.mdl" )
	AP_PrecacheModel( $"models/titans/light/sp_titan_light_locust.mdl" )
	AP_PrecacheModel( $"models/titans/light/sp_titan_light_raptor.mdl" )
	AP_PrecacheModel( $"models/titans/light/titan_light_rodeo_battery.mdl" )
	AP_PrecacheModel( $"models/titans/medium/sp_titan_medium_ajax.mdl" )
	AP_PrecacheModel( $"models/titans/medium/sp_titan_medium_wraith.mdl" )
	AP_PrecacheModel( $"models/titans/medium/titan_medium_rodeo_battery.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/buddypov.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/human_pov_cockpit.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/pov_mlt_hero_jack_rifleman.mdl" )
	AP_PrecacheModel( $"models/weapons/arms/pov_titan_medium_cockpit.mdl" )
#endif

#if !DEV

	PrecacheWeapon( "melee_pilot_emptyhanded" )
	PrecacheWeapon( "melee_titan_punch" )
	PrecacheWeapon( "melee_titan_punch_ion" )
	PrecacheWeapon( "melee_titan_punch_legion" )
	PrecacheWeapon( "melee_titan_punch_northstar" )
	PrecacheWeapon( "melee_titan_punch_scorch" )
	PrecacheWeapon( "melee_titan_punch_tone" )
	PrecacheWeapon( "melee_titan_sword" )
	PrecacheWeapon( "mp_titanability_ammo_swap" )
	PrecacheWeapon( "mp_titanability_basic_block" )
	PrecacheWeapon( "mp_titanability_gun_shield" )
	PrecacheWeapon( "mp_titanability_hover" )
	PrecacheWeapon( "mp_titanability_laser_trip" )
	PrecacheWeapon( "mp_titanability_particle_wall" )
	PrecacheWeapon( "mp_titanability_phase_dash" )
	PrecacheWeapon( "mp_titanability_power_shot" )
	PrecacheWeapon( "mp_titanability_slow_trap" )
	PrecacheWeapon( "mp_titanability_smoke" )
	PrecacheWeapon( "mp_titanability_sonar_pulse" )
	PrecacheWeapon( "mp_titanability_tether_trap" )
	PrecacheWeapon( "mp_titancore_amp_core" )
	PrecacheWeapon( "mp_titancore_flame_wave" )
	PrecacheWeapon( "mp_titancore_flight_core" )
	PrecacheWeapon( "mp_titancore_laser_cannon" )
	PrecacheWeapon( "mp_titancore_salvo_core" )
	PrecacheWeapon( "mp_titancore_shift_core" )
	PrecacheWeapon( "mp_titancore_siege_mode" )
	PrecacheWeapon( "mp_titanweapon_arc_wave" )
	PrecacheWeapon( "mp_titanweapon_dumbfire_rockets" )
	PrecacheWeapon( "mp_titanweapon_flame_wall" )
	PrecacheWeapon( "mp_titanweapon_heat_shield" )
	PrecacheWeapon( "mp_titanweapon_laser_lite" )
	PrecacheWeapon( "mp_titanweapon_leadwall" )
	PrecacheWeapon( "mp_titanweapon_meteor" )
	PrecacheWeapon( "mp_titanweapon_particle_accelerator" )
	PrecacheWeapon( "mp_titanweapon_predator_cannon" )
	PrecacheWeapon( "mp_titanweapon_rocketeer_rocketstream" )
	PrecacheWeapon( "mp_titanweapon_shoulder_rockets" )
	PrecacheWeapon( "mp_titanweapon_sniper" )
	PrecacheWeapon( "mp_titanweapon_sticky_40mm" )
	PrecacheWeapon( "mp_titanweapon_tracker_rockets" )
	PrecacheWeapon( "mp_titanweapon_vortex_shield" )
	PrecacheWeapon( "mp_titanweapon_vortex_shield_ion" )
	PrecacheWeapon( "mp_titanweapon_xo16_shorty" )
	PrecacheWeapon( "mp_weapon_car" )
	PrecacheWeapon( "mp_weapon_dmr" )
	PrecacheWeapon( "mp_weapon_dronebeam" )
	PrecacheWeapon( "mp_weapon_droneplasma" )
	PrecacheWeapon( "mp_weapon_frag_drone" )
	PrecacheWeapon( "mp_weapon_frag_grenade" )
	PrecacheWeapon( "mp_weapon_grenade_emp" )
	PrecacheWeapon( "mp_weapon_hemlok" )
	PrecacheWeapon( "mp_weapon_hemlok_smg" )
	PrecacheWeapon( "mp_weapon_lmg" )
	PrecacheWeapon( "mp_weapon_rocket_launcher" )
	PrecacheWeapon( "mp_weapon_rspn101" )
	PrecacheWeapon( "mp_weapon_semipistol" )
	PrecacheWeapon( "mp_weapon_shotgun" )
	PrecacheWeapon( "mp_weapon_smr" )
	PrecacheWeapon( "mp_weapon_turretplasma" )
	PrecacheWeapon( "mp_weapon_vinson" )
	PrecacheModel( $"models/Humans/heroes/imc_hero_slone.mdl" )
	PrecacheModel( $"models/creatures/prowler/r2_prowler.mdl" )
	PrecacheModel( $"models/gibs/human_gibs.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib7_r_shin.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib8_l_thigh2.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib9_l_bicep1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_hatch_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_l_arm2_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/at_gib_r_arm2_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/og_gib_hatch_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/og_gib_r_forarm_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib7_r_shin.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib8_l_thigh1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib8_l_thigh2.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib9_l_bicep1.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_hatch_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_l_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_l_arm2_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_r_arm1_d.mdl" )
	PrecacheModel( $"models/gibs/titan_gibs/stry_gib_r_arm2_d.mdl" )
	PrecacheModel( $"models/humans/grunts/imc_grunt_rifle.mdl" )
	PrecacheModel( $"models/humans/grunts/imc_grunt_shield_captain.mdl" )
	PrecacheModel( $"models/humans/grunts/mlt_grunt_rifle.mdl" )
	PrecacheModel( $"models/humans/heroes/imc_hero_ash.mdl" )
	PrecacheModel( $"models/humans/heroes/imc_hero_blisk.mdl" )
	PrecacheModel( $"models/humans/heroes/mlt_hero_jack_rifleman.mdl" )
	PrecacheModel( $"models/humans/pilots/sp_light_ged_m.mdl" )
	PrecacheModel( $"models/robots/aerial_unmanned_worker/aerial_unmanned_worker.mdl" )
	PrecacheModel( $"models/robots/drone_air_attack/drone_air_attack_plasma.mdl" )
	PrecacheModel( $"models/robots/spectre/imc_spectre.mdl" )
	PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_arm_l.mdl" )
	PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_arm_r.mdl" )
	PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_leg_l.mdl" )
	PrecacheModel( $"models/robots/spectre/spectre_assault_d_gib_leg_r.mdl" )
	PrecacheModel( $"models/robots/turret_plasma/turret_plasma.mdl" )
	PrecacheModel( $"models/titans/buddy/titan_buddy.mdl" )
	PrecacheModel( $"models/titans/heavy/sp_titan_heavy_deadbolt.mdl" )
	PrecacheModel( $"models/titans/heavy/titan_heavy_rodeo_battery.mdl" )
	PrecacheModel( $"models/titans/light/sp_titan_light_locust.mdl" )
	PrecacheModel( $"models/titans/light/sp_titan_light_raptor.mdl" )
	PrecacheModel( $"models/titans/light/titan_light_rodeo_battery.mdl" )
	PrecacheModel( $"models/titans/medium/sp_titan_medium_ajax.mdl" )
	PrecacheModel( $"models/titans/medium/sp_titan_medium_wraith.mdl" )
	PrecacheModel( $"models/titans/medium/titan_medium_rodeo_battery.mdl" )
	PrecacheModel( $"models/weapons/arms/buddypov.mdl" )
	PrecacheModel( $"models/weapons/arms/human_pov_cockpit.mdl" )
	PrecacheModel( $"models/weapons/arms/pov_mlt_hero_jack_rifleman.mdl" )
	PrecacheModel( $"models/weapons/arms/pov_titan_medium_cockpit.mdl" )
#endif

	#if CLIENT
	ClTitanBuddy_Init( $"models/titans/buddy/titan_buddy.mdl" )
	ClTitanAtlas_Init( $"models/titans/medium/sp_titan_medium_ajax.mdl" )
	ClTitanAtlas_Init( $"models/titans/medium/sp_titan_medium_wraith.mdl" )
	ClTitanStryder_Init( $"models/titans/light/sp_titan_light_locust.mdl" )
	ClTitanStryder_Init( $"models/titans/light/sp_titan_light_raptor.mdl" )
	ClTitanOgre_Init( $"models/titans/heavy/sp_titan_heavy_deadbolt.mdl" )
	#endif
}

