name: Search for missing translations
on: [push, pull_request]

jobs:
  check-missing-translations:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Look out for missing translations
        run: node build/find-missing-translations.js